### ISSUE TITLE
api change?

### ISSUE THREAD

**Issue by MasterPi-2124** [notional-labs/app.digchain.org#60]
{,…}
error: "this transaction cannot be displayed via legacy REST endpoints, because it does not support Amino serialization. Please either use CLI, gRPC, gRPC-gateway, or directly query the Tendermint RPC endpoint to query this transaction. The new REST endpoint (via gRPC-gateway) is /cosmos/tx/v1beta1/txs. Please also see theREST endpoints migration guide at https://docs.cosmos.network/master/migrations/rest.html for more info"

**Comment by sontrinh16** [comment]
please specifi the problem
